### ISSUE TITLE
[Request] Add additional information to logs.

### ISSUE THREAD

**Issue by slimshizn** [kevtainer/denyip#12]
It may be beneficial to add in additional information such as which container was attempted to be accessed to the log.

**Comment by kvncrw** [comment]
> It may be beneficial to add in additional information such as which container was attempted to be accessed to the log.

Are you referring to which traefik container has handled the request? This is a dimension which should be obtainable assuming you're using a logger which captures details such as container name, region, host, etc. Most logging agents should either do this by default or can be configured to do so.

**Comment by slimshizn** [comment]
No,  I'm referring to which container behind traefik the attempt is being made. As it stands if I have two applications behind traefik that use denyip, I cant tell which application is being denied based on denyips current logging. Let me know if you need more information.

**Comment by kvncrw** [comment]
Would logging the rules `service` association make sense here?

eg:

```
http:
  # Add the router
  routers:
    my-router:
      entryPoints:
      - http
      middlewares:
      - denyip
      service: service-foo        <--- log this    
      rule: Path(`/foo`)
```
