### ISSUE TITLE
Plugin Not working with traefik 3.4.1

### ISSUE THREAD

**Issue by vladislavs1321** [kevtainer/denyip#15]
```
 error="unable to set up plugins environment: unable to download plugin github.com/kevtainer/denyip: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/kevtainer/denyip/v2.0.0\": GET https://plugins.traefik.io/public/download/github.com/kevtainer/denyip/v2.0.0 giving up after 4 attempt(s)" plugins=["denyip"]
```
 part of deployment running config:
```
containers:
        - name: traefik
          image: docker.io/traefik:v3.4.1
          args:
            ...
            - '--experimental.plugins.denyip.moduleName=github.com/kevtainer/denyip'
            - '--experimental.plugins.denyip.version=v2.0.0'
            ...
  ```
